### ISSUE TITLE
Add `http:` and `https:` specifiers for `deno add`

### ISSUE THREAD

**Issue by tristanisham** [denoland/deno_semver#19]
Add `http:` and `https:` specifiers for `deno add`. 

## Example
`deno add https:example.com/mod.ts`

This is in reference to [this Deno issue](https://github.com/denoland/deno/issues/23216).

**Comment by dsherret** [comment]
I don't believe this needs to be added here? The only urls here are semvered urls.

**Comment by tristanisham** [comment]
Is here a more appropriate place to add support for additional specifiers? I saw that NPM and JSR were both implemented here so I thought this might be the place.

**Comment by dsherret** [comment]
`https`/`http` specifiers are already used a lot throughout deno. I don't believe they need to be added here just for `deno add`.

**Comment by tristanisham** [comment]
That's fine. I'll refocus back on the main repository.
