### ISSUE TITLE
Unsupported range ^=

### ISSUE THREAD

**Issue by zllak** [denoland/deno_semver#22]
I'm working on a project, and I use `deno_semver` to parse projects `package.json` file.
I stumbled upon a version requirement in the form of `^= 8.0.0`, which deno_semver does not recognize.
At checked with the official node semver library:
```typescript
const semverValidRange = require('semver/ranges/valid')

semverValidRange('^=8.0.0');
```

This parses correctly and return the proper range.

Can we add support for this syntax on here ?
If someone knows exactly how to fix this, that would be awesome, otherwise, can someone point me in the right file so I can propose a PR to fix this ?

Thanks

**Comment by dsherret** [comment]
Yeah, it can be fixed here: https://github.com/denoland/deno_semver/blob/0cff13bdb24318e7c7423e22360b2e4e8bbdd585/src/npm.rs#L88

Based on what the semver npm package returns, it looks like `^=8.0.0` is just `^8.0.0`.

**Comment by zllak** [comment]
PR has been merged, thank you for the quick reaction ! :)
